### ISSUE TITLE
Hi？

### ISSUE THREAD

**Issue by iioter** [IOT-CS/IOTCS#1]
兄弟，请问你是在模仿我么？

**Comment by IOT-CS** [comment]
前辈您好！工业物联网平台网关，我们是参考先进物联网软网关的设计理念。我们也不知道在某一个方向上跟您有所雷同了，那纯属巧合，该项目我们从构思启动到上线已有接近2年的时间，请前辈查看我们的源码。如有疑问，随时可以私聊沟通。也希望我们可以共同进步。
